sonar.projectKey=template-service
sonar.projectName=template-service
sonar.sources=src
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.spec.ts,**/test/**,**/*.module.ts